name: bd_money_formatter
description: "Flutter package for convert Number to Bangladesh (BD) Money Format, BD money format different than other country, Most of the country write as '12,34,56' but in Bangladesh write as 1,23,456 formation"
version: 1.0.0
homepage: https://github.com/Pritom-Chaki/bd_money_formatter
repository: https://github.com/Pritom-Chaki/bd_money_formatter

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
